# Generated by Django 3.2.7 on 2021-10-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('highlights', models.TextField(null=True)),
            ],
        ),
    ]
