# Generated by Django 3.2.7 on 2021-10-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='SchoolGrade',
        ),
    ]
