# Generated by Django 3.2.7 on 2022-01-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20220105_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolgrade',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
